name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: sreekesh26/itemsapi
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSWORD }}
          port: 22
          script: |
            echo "Pulling latest Docker image..."
            docker pull sreekesh26/itemsapi:latest
            echo "Stopping and removing existing container..."
            docker stop itemsapi || true
            docker rm itemsapi || true
            echo "Running new Docker container..."
            docker run -d --name itemsapi -p 8080:8080 sreekesh26/itemsapi:latest
            echo "Deployment completed successfully!"
